### ISSUE TITLE
How to reproduce

### ISSUE THREAD

**Issue by ogges** [kkthxbye-code/csgo_bugs#1]
Hello kkthxbye,

im trying to reproduce this bug on the new d2 (it still have packed props..), but im in struggle to follow you steps. Maybe you can explain them a bit better?

Decompile de_cache (with the packed props). --> Decompiled de_dust2 with bspsrc

I created a map, wanted to load the model autocombine_hr_dust_stairs001_color_478.vvd but every time i get the error : Unable to load vertex data "models/props/autocombine/de_dust2/_autocombine_hr_dust_stairs001_color_478.vvd"

Maybe you can make a more detailed tutorial how to do it correct?

Greetings

**Comment by kkthxbye-code** [comment]
@ogges - I don't really have the time. If you can't load the model it's probably missing files, the files are in the wrong location or you messed up when editing the checksum.

**Comment by ogges** [comment]
They did changed some stuff on d2. I made a map with the new manipulated models but only short stairs worked. Do you have any information about that?

**Comment by kkthxbye-code** [comment]
@ogges - Nope, the map I made was just me scripting the corruption of all possible props. If only one works, maybe they included the props in the pak files instead, in which case you can't corrupt them.

**Comment by kkthxbye-code** [comment]
Not gonna be elaborating any time soon, so closing this.
