### ISSUE TITLE
how to edit vtx?

### ISSUE THREAD

**Issue by theFreeWall** [kkthxbye-code/csgo_bugs#2]
"edit checkSum of FileHeader_t for the corrosponding .vtx file "
I decompiled the map with "bspsrc"and got the vmf file
Then use gcfscape to find the corresponding mdl, vtx, vdd, phy files from the vpk and export them
But I have no way to edit the vtx file, is there any tool? The hammer doesn't seem to modify it directly
I am a beginner and have been searching for 7 hours with Google but still no answer

**Comment by kkthxbye-code** [comment]
Use a hex editor, the header definition can be seen here:
https://developer.valvesoftware.com/wiki/VTX#Header

We are interested in checksum, so before the checksum we have:

    int version;
    int vertCacheSize;
    unsigned short maxBonesPerStrip;
    unsigned short maxBonesPerTri;
    int maxBonesPerVert;

int is 4 bytes
unsinged short is 2 bytes

So the checksum is at an offset of 16 bytes.

![image](https://user-images.githubusercontent.com/400797/70931984-f2ae7b80-2038-11ea-9798-76c52bc786b2.png)

**Comment by theFreeWall** [comment]
thanks!

**Comment by semisurrr** [comment]
Would you be changing all 4 bytes or just changing 15?

**Comment by hinnie123** [comment]
> Would you be changing all 4 bytes or just changing 15?

All 4, as a 32-bit int(eger) is 4 bytes.

**Comment by semisurrr** [comment]
@hinnie123 Is there anywhere I can contact you?  I am currently in the process of reproducing this bug and would like to understand the steps in further detail.

**Comment by semisurrr** [comment]
I managed to change the checksum by editing the first byte.  But instead of getting a Vertex file error, I get a Index file error.  Any clue why?
