### ISSUE TITLE
Setup file 'gameinfo.txt' doesn't exis in subbredirectory 'csgo'. Check your -game parameter or VCONFIG setting.

### ISSUE THREAD

**Issue by Spitfirexd** [kkthxbye-code/csgo_bugs#20]
it says that when i try to launch csgo

Setup file 'gameinfo.txt' doesn't exis in subbredirectory 'csgo'. Check your -game parameter or VCONFIG setting.

**Comment by mbhound** [comment]
You don't need to touch 'gameinfo.txt'. Reverify your game files and download the files in the google drive link instead.
