### ISSUE TITLE
bypass_7 - I'm not sure if the mirror.exe is working, read below

### ISSUE THREAD

**Issue by DoKnocK** [kkthxbye-code/csgo_bugs#28]
I followed instruction, created an empty csgo folder after renaming the existing to csgo_bak folder.

Next step is to run the command as admin

mirror.exe /r "C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo_bak" /l "C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo"

So, I open my cmd as admin, navigate to folder C:\Program Files\Dokan\DokanLibrary-1.4.0\sample\mirror and then run 

C:\Program Files\Dokan\DokanLibrary-1.4.0\sample\mirror>mirror.exe /r "C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo_bak" /l "C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo"

I see that the newly created csgo folder is now a mounted volume but on the cmd prompt, I dont get any message as success or failed, how long does the mirroring take ? do we get any confirmation message on cmd prompt once the mirroring is done ?

Reason am asking is because it's still mirroring the folder so when I go to edit the pak file in the next steps, it doesnt let me save the PAK file as it's still in use with the cmd prompt.

Any help ?

![image](https://user-images.githubusercontent.com/68970953/92576959-bfd3a400-f2a7-11ea-9657-4c28c1f1b99c.png)

![image](https://user-images.githubusercontent.com/68970953/92576997-c95d0c00-f2a7-11ea-811c-fab9ebda5ffa.png)

**Comment by sjain882** [comment]
Same issue here, restarted PC after installing Dokan, and tried putting mirror.exe in the Counter-Strike Global Offensive folder, and setting cmd path to there and running from there, but nothing.
My explorer looks like this:
![image](https://user-images.githubusercontent.com/43217178/92653351-1e1f7780-f2e6-11ea-9fb5-9360020697df.png)

**Comment by szmarczak** [comment]
> I see that the newly created csgo folder is now a mounted volume but on the cmd prompt, I dont get any message as success or failed, how long does the mirroring take ?

No error is a success.

> do we get any confirmation message on cmd prompt once the mirroring is done ?

Yes, when you `ctrl+c` you'll see `Success`.

> it doesnt let me save the PAK file as it's still in use with the cmd prompt.

No, it's not. You're opening the .vpk file inside `csgo`. From the docs:

> Open it in notepad++ (make sure it's csgo_bak and NOT csgo).

**Comment by szmarczak** [comment]
https://www.youtube.com/watch?v=gkY9T3JdndY
