### ISSUE TITLE
Appears to be fixed.

### ISSUE THREAD

**Issue by sjain882** [kkthxbye-code/csgo_bugs#29]
Just tested exactly as demonstrated in the instructions and the video, but the game kicks me every time, saying the game file does not match (for pak01_008.vpk).

I tried multiple times, and on different accounts, and on a clean install of CS, but no luck

**Comment by szmarczak** [comment]
It still works after the 08th September update.

**Comment by sjain882** [comment]
> It still works after the 08th September update.

Thanks for confirming this, but any ideas what to do? I tried everything 1:1 as per instructions, and all the alternative methods, and i tried deleting my csgo folder then verifying game files, and a clean reinstall too, and retrying from scratch but it always fails, with the validation error. Any ideas or scraps of info i can use? No idea

**Comment by szmarczak** [comment]
Me neither :|
