### ISSUE TITLE
generateWallhack.js

### ISSUE THREAD

**Issue by klops-za** [kkthxbye-code/csgo_bugs#36]
Hi I get this error running the Node commands

D:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo_bak>node generateWallhack.js
D:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo_bak\generateWallhack.js:4
        if (i  10) {
               ^^

SyntaxError: Unexpected number
←[90m    at wrapSafe (node:internal/modules/cjs/loader:1018:16)←[39m
←[90m    at Module._compile (node:internal/modules/cjs/loader:1066:27)←[39m
←[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)←[39m
←[90m    at Module.load (node:internal/modules/cjs/loader:967:32)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:807:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)←[39m
←[90m    at node:internal/main/run_main_module:17:47←[39m

**Comment by kkthxbye-code** [comment]
Copy paste error looks like, the line should be:

`	if (i < 10) {`
