### ISSUE TITLE
I cant use, the game sound still´s the same

### ISSUE THREAD

**Issue by pattiatri** [kkthxbye-code/csgo_bugs#4]

**Comment by szmarczak** [comment]
You must've done something wrong. It works for me.

**Comment by kkthxbye-code** [comment]
This is mostly a repo for myself, not somewhere you can get support.

**Comment by pattiatri** [comment]
it not just to put the .txt into that folder? I copy the content and paste on a .txt folder, and put in to steamapps\common\Counter-Strike Global Offensive\platform\scripts\ and nothing happens.. I make something wrong?

**Comment by Itzsamxx** [comment]
me too i copied the text file to scripts and restarted , nothing happens still working with the default sounds

**Comment by b3asti** [comment]
Same here please help!
