### ISSUE TITLE
can't open cs:go

### ISSUE THREAD

**Issue by ihhashi** [kkthxbye-code/csgo_bugs#41]
as soon as i try to open the game, it tells me that there is an error because the file "pak01_016.vpk" is corrupted

**Comment by Billar42** [comment]
What is the bug of launching sv_pure_bypass_7_2 or sv_pure_bypass_8?

**Comment by ihhashi** [comment]
i tried sv_pure_bypass 6

**Comment by Billar42** [comment]
![Снимок](https://user-images.githubusercontent.com/75508060/101386876-cab1cb00-38ce-11eb-892c-ffc51e366595.PNG)

**Comment by szmarczak** [comment]
verify game files, solved.
