### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by yejun2606** [kkthxbye-code/csgo_bugs#44]
Hello, I followed the recent sv_pure_bypass 8 steps. When I tried to run wallhack.js, it shows an error. How to fix it?
![capture1](https://user-images.githubusercontent.com/33985532/101846938-0083d780-3b8d-11eb-953f-bbdb9cbc2620.PNG)
![Capture](https://user-images.githubusercontent.com/33985532/101846942-024d9b00-3b8d-11eb-8a36-9722d19cb6d5.PNG)

**Comment by kkthxbye-code** [comment]
Follow the steps. Run it with node.
