### ISSUE TITLE
Sv_pure_bypass 8 work on faceit or 9?

### ISSUE THREAD

**Issue by doom66666** [kkthxbye-code/csgo_bugs#46]
Sv_pure_bypass 8 work on faceit or 9?

**Comment by kkthxbye-code** [comment]
Not a support forum.

**Comment by Billar42** [comment]
sv_pure_bypass_8 works on faceit, but you can get banned forever

**Comment by rafalohaki** [comment]
> sv_pure_bypass_8 works on faceit, but you can get banned forever

U can but u wont if u know how to play legit.

**Comment by doom66666** [comment]
dont work on faceit he say vpk file 01_9 is modified or something like that
