### ISSUE TITLE
bug dont working anymore

### ISSUE THREAD

**Issue by doom66666** [kkthxbye-code/csgo_bugs#47]
Bug dont work after the update the vpk files is corrupt .Any help?

**Comment by Billar42** [comment]
Delete old backup files in csgo folder

**Comment by Billar42** [comment]
![Снимок](https://user-images.githubusercontent.com/75508060/102668279-95459100-419c-11eb-8942-ca4c0741dc3c.PNG)

**Comment by FawkesOficial** [comment]
It still works for me tho. Although I have to say that when I tested it after the update I needed to reload CSGO every time I would want to switch maps, because otherwise, when joining a new server, it would say that the files were corrupted, but it still works if I just reload the game.

**Comment by Billar42** [comment]
Everything has its drawbacks, it's easier for me personally, it's just that my script is rewritten

**Comment by doom66666** [comment]
> Everything has its drawbacks, it's easier for me personally, it's just that my script is rewritten


First of all, I would like to thank you for your work and I really appreciate it and I deleted files 00 and 01 because it gave me corrupt ones and after I deleted them it worked, I haven't tried it yet, I have money until tomorrow
