### ISSUE TITLE
Sv_pure_bypass_8  it doesn't work for me on faceit

### ISSUE THREAD

**Issue by Billar42** [kkthxbye-code/csgo_bugs#48]
3 days ago, Russian-speaking users updated their anti-cheat for csgo and today I run faceit ac does not work when disabled the bug works in mm and danger zone

**Comment by Billar42** [comment]
Could you check this on your computers?

**Comment by doom66666** [comment]
the chat work for me after i delete vpk00 and vpk001

**Comment by Billar42** [comment]
After any replacement of vpk during the game, cs go crashes
