### ISSUE TITLE
There could be a chance that sv_pure_bypass_8 is fixed

### ISSUE THREAD

**Issue by eren-erver** [kkthxbye-code/csgo_bugs#49]
When I try to execute wallhack.js it doesn't recognize netcon.
My launch options: -novid -netconport 2121
This is the console output:

Tip: to revert changes simply close CS:GO. If closed already, press CTRL+C here.
Found 5 properties in pak01_000.vpk
Backup already exists. Skipping.
Found 1 properties in pak01_001.vpk
Backup already exists. Skipping.
Found 1 properties in pak01_004.vpk
Backup already exists. Skipping.
Found 17 properties in pak01_007.vpk
Backup already exists. Skipping.
Found 37 properties in pak01_008.vpk
Backup already exists. Skipping.
Found 49 properties in pak01_009.vpk
Backup already exists. Skipping.
Found 41 properties in pak01_010.vpk
Backup already exists. Skipping.
Found 16 properties in pak01_011.vpk
Backup already exists. Skipping.

Renaming csgo to csgo_bak...
Bypassing write access lock via WinFSP...

You can now launch CS:GO.
Connecting to port 2121...

//I launch csgo , connect to a server and nothing happens

//after closing csgo and pressing ctrl + c in console

Closing CS:GO.
Reverting changes.
Renaming csgo_bak back to csgo...
Done.

**Comment by Billar42** [comment]
Download pre-compiled passthrough-x64.exe or compile it yourself.

**Comment by Billar42** [comment]
??

**Comment by kkthxbye-code** [comment]
Don't think netcon has been removed, so closing this. Open another one with proof if you are sure.
