### ISSUE TITLE
wallhack.js EPERM error 

### ISSUE THREAD

**Issue by yeetos360** [kkthxbye-code/csgo_bugs#52]
I get to renaming csgo to csgo bak and then it gives me the classic EPERM -4048 error. I have the latest npm version and even cleaned npm cache with --force, I don't know what to do anymore.

**Comment by Billar42** [comment]
hahah check sv_pure_bypass_8 more attentively

**Comment by Billar42** [comment]
Install Node.js.
If you're not running Windows, skip this step.
Install WinFSP (necessary for mirroring the VPK files)
Download pre-compiled passthrough-x64.exe or compile it yourself.
Add -netconport 2121 to launch options.
Update CSGO_EXE_DIR and VIDEO_FILE constants in the wallhack.js file. Note that on Windows you need to use \\ to add a backslash.
Run node wallhack.js
Wait till you see Connecting to port 2121...
Run CS:GO and connect to any server.
Profit!
To revert changes either close CS:GO or press CTRL+C in the terminal (this will close CS:GO on Windows).

**Comment by Billar42** [comment]
where did you see what you rename?

**Comment by yeetos360** [comment]
I've updated CSGO_EXE_DIR and VIDEO_FILE with my right directories before I even ran it with node,and when I do run it with node,it creates backups for the vpk files but then it gives the EPERM error (couldn't rename ....csgo to ...csgo_bak)

**Comment by yeetos360** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/77511598/104951224-ce0a9d00-59ca-11eb-80ec-fa5ff7588863.png)

**Comment by jama9999** [comment]
"not permitted" try to change the folders settings or change the directory

**Comment by Billar42** [comment]
I can help in the installation even do better than 
szmarczak I did some flaws

**Comment by Billar42** [comment]
in discord

**Comment by yeetos360** [comment]
> "not permitted" try to change the folder's settings or change the directory

![Screenshot (5)](https://user-images.githubusercontent.com/77511598/105003924-eff03800-5a3b-11eb-8cf1-083817e9a8f6.png)

I have changed csgo's directory and updated it in the script. I guess the problem is something related to node,since the script does its job and creates backups for vpk files.

**Comment by jama9999** [comment]
hey, i had the same problem yesterday... as i saw backups was already existing so you just have to delete them and let the node creating them again and its gonna work, at least in my pc it starts working again

**Comment by yeetos360** [comment]
> hey, i had the same problem yesterday... as i saw backups was already existing so you just have to delete them and let the node creating them again and its gonna work, at least in my pc it starts working again... BUT Im still getting crush on MM, as on faceit

Did not work for me :/ . But thanks for the suggestion.

**Comment by Billar42** [comment]
Close the issue and try using sv_pure_bypass 7_2 it still works
