### ISSUE TITLE
sv_pure_bypass_9

### ISSUE THREAD

**Issue by kepik12345** [kkthxbye-code/csgo_bugs#59]
Please update the link (materials.zip).

**Comment by Billar42** [comment]
Updated close issue

**Comment by Jolle12321** [comment]
update link ("materials.zip") please

**Comment by Billar42** [comment]
Hello, in my opinion there is no use it because all large sites have already made their fix, and you can generate a wallhack on the community servers via pak01_dir.vpk, it is not difficult for more details in sv_pure_bypass 4 or at https://developer.valvesoftware.com/wiki/ VPK
close issue
