### ISSUE TITLE
Hello, how to turn off the current status

### ISSUE THREAD

**Issue by tengrongkeji** [kkthxbye-code/csgo_bugs#64]
Hello, how to turn off the current status
![image](https://user-images.githubusercontent.com/52775252/113431197-e46da580-93ca-11eb-8381-200c03ba9af1.png)

**Comment by Billar42** [comment]
Hello, go to local files csgo \ materials and delete folders, dust and models.

**Comment by Billar42** [comment]
Close pls. Problem solved
