### ISSUE TITLE
need old wallhack.js

### ISSUE THREAD

**Issue by jama9999** [kkthxbye-code/csgo_bugs#67]
can someone share old wallhack.js for bypass 8, cuz new one from 7.2 is not working completely. i dont see t side on any map

**Comment by HackerPide** [comment]
https://github.com/kkthxbye-code/csgo_bugs/raw/e94ffde14a4c8c333b11fa1cf06be1c93b871e83/sv_pure_bypass_8/wallhack.js

**Comment by jama9999** [comment]
appreciate

**Comment by Billar42** [comment]
const PAK_FILES = [
	'pak01_007.vpk',
	'pak01_009.vpk',
	'pak01_010.vpk',
	'pak01_011.vpk'
];
