### ISSUE TITLE
sv_pure_bypass_8 works only on default CT models?

### ISSUE THREAD

**Issue by aniketraj1947** [kkthxbye-code/csgo_bugs#69]
Tried using sv_pure_bypass_8 on Mirage, it did work after changing the Shader Settings to low. However, it was working only on 2 out of 5 CTs. I figured it out through other maps as well that it works only on default CT models. Is it true or is there a way around this?

**Comment by Billar42** [comment]
vpk is constantly changing and sv_pure_bypass 8 has its drawbacks try using sv_pure_bypass 7_2 my models work stably
