### ISSUE TITLE
Vac

### ISSUE THREAD

**Issue by jama9999** [kkthxbye-code/csgo_bugs#72]
I just wanted to know, does valve bans accounts for using this? Maybe already did to someone?

I used to use this node for 2-3 month but it all was legit.

I want to invest on my profile, it's already steam level 200 and I have some expensive skins. Moreover I want to buy some stuff for ≈1k$ in near future

**Comment by Billar42** [comment]
Hi, my name is Artem. Our repository is given to valve as a tool to fix it, and not to use it for an advantage in the game. If in secret I professionally do cheats on FaceIt and I can bypass it whenever I want and nothing will happen to me. If you want to cheat on Esea, Fastcap, Faceit, then you will not succeed so they fix files that are in the public domain. If you want to play Matchmaking, then, with pleasure, but there may be a patrol for this. And I immediately say I will not sell my cheats on Faceit and Esea, it would be stupid of me to spoil their reputation without receiving a very huge reward.

**Comment by Billar42** [comment]
Nevertheless, do not spend money on this game, sooner or later anything can happen, including account bans

**Comment by szmarczak** [comment]
> does valve bans accounts for using this? Maybe already did to someone?

Nope. They already have proven they don't care. Or, at least aren't capable of fixing this.

> I want to invest on my profile, it's already steam level 200 and I have some expensive skins. Moreover I want to buy some stuff for ≈1k$ in near future

I highly suggest you don't do this. That's quite lots of money and you still can get overwatch'd.
