### ISSUE TITLE
bypass 8 and bypass 7_2 doesnt work

### ISSUE THREAD

**Issue by paryzius** [kkthxbye-code/csgo_bugs#77]
Bypass 8 throws an EPERM error about not being able to rename csgo to csgo_bak and bypass 7_2 mirror.exe cant find dokany1.dll
@Billar42 could I talk about this with you on discord?

**Comment by Billar42** [comment]
These branches no longer work (possibly due to outdated vpk) about relevance dokan.dll I can't say anything because I don't do it anymore
